### ISSUE TITLE
Unable to squash pull request when branch is an org

### ISSUE THREAD

**Issue by sstok** [gushphp/gush#213]
When using 'pull-request:squash' the `['head']['user']` of the PR is used, but (at least for GitHub) when your not using a fork the command fails because `['head']['user']` returns the name of the organization and not the PR owner.

We have a few options for this:

1. Leave as-is, mark is as a limitation.
2. Check if `['head']['user']` equals the value of ``--org` and allow the push. Could be problematic as we don't check if the user has pushing rights on the repository.
3. Check if `['head']['user']` equals the value of ``--org`, and use the `pr['user']` instead for the validating (actually the best option, and popped in my head (no pun) just now :smiley: )

But there is still one other problem, by default the username is used while I use origin for the remote-name. So we should add an optional argument for that as well.

**Comment by cordoval** [comment]
is this still an issue @sstok how to reproduce?

**Comment by sstok** [comment]
I think the only real way to fix this is to remove the check and just try it, if it fails it fails if works it work it works :)

**Comment by sstok** [comment]
@cordoval Are you ok with removing the check and just letting the adapter respond with an error?

**Comment by cordoval** [comment]
let's remove the check yes, it simplifies things and makes things bearable.

**Comment by sstok** [comment]
Ok :+1: .
