### ISSUE TITLE
DynamicLabels for adapter supporting none-fixed labels

### ISSUE THREAD

**Issue by sstok** [gushphp/gush#245]
Reminder for.
https://github.com/gushphp/gush-jira-adapter/pull/4/files#r14504451

> OK, so we should try to fix this in Gush application instead of marking this as not possible. For now we can keep this exception, but for future we properly want to get this fixed.

> The first thing I can think of is adding a 'feature' interface like, DynamicLabelsAware or something like that, the issue commands can then detect if this interface is implemented and skip the validation of existence.

Not all adapters/issue-tracker work with fixed labels and we should provide support for this.
Allowing the end-user to just fill-in labels as he wants.

**Comment by cordoval** [comment]
@sstok i think @jacobkiers is also in NL :baby: just was thinking if you have met him

basically let's close this ticket if there is no interest? I think @jucobkiers uses it with jira but i am not sure if there is a need for this.

**Comment by sstok** [comment]
Well if Jira needs it we can still support it :) its not to complicated but I need to find some time.
I'm currently working on the completion of RollerworksSearch and is its a bit hectic in my personal life :anger:.

**Comment by jacobkiers** [comment]
@cordoval No, we haven't met yet.

Thank you for thinking of me in this ticket. We're not currently using labels, but we're going to introduce them somewhere in this quarter. I want to start using them to track custom properties that are just a bit too dynamic to deal with in custom fields or components.

@sstok I might be able to find some time for this also. Could you give me some pointers as to where I should start?

**Comment by sstok** [comment]
First we we need a marker interface to indicate an issue-tracker/repository supports Dynamic labeling.
Then LabelIssuesCommand needs to be updated that when an issue-tracker with dynamic labeling support is given the user can just type labels and is not required to choose from a list.

**Comment by sstok** [comment]
I will get working on this (I actually I'm already :) )

**Comment by sstok** [comment]
He thats cool, GitHub accepts dynamic labels :) it will automatically create a new label if it doesn't existent.

**Comment by cordoval** [comment]
interesting

**Comment by cordoval** [comment]
should we close this one now that it got merged?

**Comment by cordoval** [comment]
@sstok ?
