### ISSUE TITLE
enable dual flow as a setting

### ISSUE THREAD

**Issue by cordoval** [gushphp/gush#358]
allow the option on .gush.yml to set whether the flow is on the same repository or on forks.
This way it will come very handy for people who use one flow or the other.

**Comment by sstok** [comment]
:+1: I have a combined idea to support this and also fix some other issues (having to always use `--org`). And even better :) its possible for 1.x :dancer: 

In short we listen for command add, but if we instead update the input definition when executing the command the adapters are available! This is only a problem for list and help so I need to find something for that (but that will work :8ball:  )
