### ISSUE TITLE
pull-request merge making changes not made in PR

### ISSUE THREAD

**Issue by tmilos** [gushphp/gush#371]
Made a test repo https://github.com/aerialship/test
Forked it to https://github.com/tmilos/test 

Made first test PR https://github.com/aerialship/test/pull/2 and it produced merged changes https://github.com/aerialship/test/commit/8cea6dc5b002ea80275ab48aea3addf24ba1885e ... All well

Problematic is next PR https://github.com/aerialship/test/pull/3/files with changes on only one file, but after ```gush pull:merge --squash 3``` it makes changes on 3 files https://github.com/aerialship/test/commit/15b0e158d848f3b74f2545e01f296c09be3d9078

Here's the log

```
d:\www\home\aerial\test>gush pull:merge --squash 3 -vvv
CMD "git" "config" "--local" "--get" "remote.aerialship.url"
CMD "git" "config" "--local" "--get" "remote.aerialship.url"

[INFO] Adding remote 'aerialship' with 'git@github.com:aerialship/test.git' to git local config.
CMD "git" "config" "--local" "--get" "remote.aerialship.url"
CMD "git" "config" "--local" "--get" "remote.aerialship.url"
CMD "git" "config" "remote.aerialship.url" "https://github.com/aerialship/test.git" "--local"
CMD "git" "config" "--local" "--get" "remote.aerialship.pushurl"
CMD "git" "config" "remote.aerialship.pushurl" "git@github.com:aerialship/test.git" "--local"
CMD "git" "config" "--local" "--get" "remote.tmilos.url"
CMD "git" "config" "--local" "--get" "remote.tmilos.url"

[INFO] Adding remote 'tmilos' with 'git@github.com:tmilos/test.git' to git local config.
CMD "git" "config" "--local" "--get" "remote.tmilos.url"
CMD "git" "config" "--local" "--get" "remote.tmilos.url"
CMD "git" "config" "remote.tmilos.url" "https://github.com/tmilos/test.git" "--local"
CMD "git" "config" "--local" "--get" "remote.tmilos.pushurl"
CMD "git" "config" "remote.tmilos.pushurl" "git@github.com:tmilos/test.git" "--local"
CMD "git" "rev-parse" "--abbrev-ref" "HEAD"
CMD "git" "status" "--porcelain" "--untracked-files=no"
CMD "git" "rev-parse" "--abbrev-ref" "HEAD"
CMD "git" "rev-parse" "--abbrev-ref" "HEAD"
CMD "git" "remote" "update" "aerialship"
CMD "git" "reset" "--hard" "HEAD~1"
CMD "git" "pull" "-u" "aerialship" "master"
CMD "git" "remote" "update" "tmilos"
CMD "git" "checkout" "tmilos/bar"
CMD "git" "checkout" "-b" "tmp--tmilos--bar"
CMD "git" "status" "--porcelain" "--untracked-files=no"
CMD "git" "rev-parse" "--abbrev-ref" "HEAD"
CMD "git" "checkout" "tmp--tmilos--bar"
CMD "git" "--no-pager" "log" "--oneline" "--no-color" "--format=%ae" "master..tmp--tmilos--bar"
CMD "git" "--no-pager" "log" "--oneline" "--no-color" "--format=%H" "--reverse" "master..tmp--tmilos--bar"
CMD "git" "--no-pager" "show" "--format=%an <%ae>%n%s%n%n%b" "--no-color" "--no-patch" "031aa4a219758134cb1bea02b7cc9ae393cd9af8"
CMD "git" "reset" "--soft" "master"
CMD "git" "commit" "-F" "C:\Users\mtomic\AppData\Local\Temp\gush\571E.tmp" "-a" "--author" "Milos Tomic <tmilos@gmail.com>"
CMD "git" "--no-pager" "log" "--oneline" "--no-color" "--format=%H" "--reverse" "master..tmp--tmilos--bar"
CMD "git" "--no-pager" "show" "--format=%an <%ae>%n%s%n%b" "--no-color" "--no-patch" "110e31b813faeef9f4a4784d5e4d116ad5965b9d"
CMD "git" "status" "--porcelain" "--untracked-files=no"
CMD "git" "rev-parse" "--abbrev-ref" "HEAD"
CMD "git" "checkout" "master"
CMD "git" "merge" "--no-ff" "--no-commit" "tmp--tmilos--bar"
OUT Removing doc/foo.md
OUT Automatic merge went well; stopped before committing as requested
CMD "git" "commit" "-F" "C:\Users\mtomic\AppData\Local\Temp\gush\5804.tmp"
OUT [master 15b0e15] merge #3 Bar (tmilos)
CMD "git" "rev-parse" "HEAD"
CMD "git" "push" "aerialship" "master"
CMD "git" "remote" "update" "aerialship"
CMD "git" "notes" "--ref=github-comments" "add" "-F" "C:\Users\mtomic\AppData\Local\Temp\gush\94B3.tmp" "15b0e158d848f3b74f2545e01
f296c09be3d9078"
CMD "git" "push" "aerialship" "refs/notes/github-comments"
This PR was squashed before being merged into the master branch (closes #3).
CMD "git" "branch" "-D" "tmp--tmilos--bar"

d:\www\home\aerial\test>
```
gush 1.14.1, php 5.4.19, windows 7 x64

Just to be sure, tried it three times :) but always same results

**Comment by cordoval** [comment]
ping @tmilos were you able to reproduce this again? what is the status?

**Comment by tmilos** [comment]
Did nothing with this so far, but now tried it again and reproduced it, this time with one merge only - the first one. 

Not sure where exactly the problem is, don't have time to dig into it, but seems the problem is with outdated base of the PR, and merge reverting changes made on upstream after PR base, probably resetting on to the wrong base. 

Here's what I did

Made new repo https://github.com/aerialship/test2
Created index.md and pushed it https://github.com/aerialship/test2/commit/8420a7bd17b201b90c18574948e5cfca2fb25cc5
Forked it to https://github.com/tmilos/test2
On main https://github.com/aerialship/test2 repo, created two additional commits:
 * foo - added foo.md https://github.com/aerialship/test2/commit/cce3ebbf0a0107678919a66777ba7f3b842b605d
 * bar - added bar.md https://github.com/aerialship/test2/commit/4b681cce62ba95b64886f1803b7adf02c3bdf3b1

Then on the fork https://github.com/tmilos/test2 (which is still on old base https://github.com/aerialship/test2/commit/8420a7bd17b201b90c18574948e5cfca2fb25cc5 where index.md was created, w/out foo.md and bar.md) made changes to index.md and created a PR https://github.com/aerialship/test2/pull/3
After running ```gush pull:merge --squash 3``` files foo.md and bar.md were deleted https://github.com/aerialship/test2/commit/271ce298200379a594a08c7d97d3449351972cab

So, it was something like this

Before merge
```
* aerislhip/master bar.md added
* foo.md added
| * tmilos/aaa pr/3 index.md changes
|/
* index.md
* initial
```

After merge
```
* aerialship/master merge #3
|\
| * index.md.changes - index.md modified (ok), foo.md and bar.md deleted (wrong)
|/
* bar.md added
* foo.md added
| * tmilos/aaa index.md some more changes
| * index.md changes
|/
* index.md
* initial
```

Here's the log
```
D:\www\home\aerial\test2>gush pull:merge --squash -vvv 3
CMD "git" "config" "--local" "--get" "remote.aerialship.url"
CMD "git" "config" "--local" "--get" "remote.aerialship.url"

[INFO] Adding remote 'aerialship' with 'git@github.com:aerialship/test2.git' to git local config.
CMD "git" "config" "--local" "--get" "remote.aerialship.url"
CMD "git" "config" "--local" "--get" "remote.aerialship.url"
CMD "git" "config" "remote.aerialship.url" "https://github.com/aerialship/test2.git" "--local"
CMD "git" "config" "--local" "--get" "remote.aerialship.pushurl"
CMD "git" "config" "remote.aerialship.pushurl" "git@github.com:aerialship/test2.git" "--local"
CMD "git" "config" "--local" "--get" "remote.tmilos.url"
CMD "git" "config" "--local" "--get" "remote.tmilos.url"

[INFO] Adding remote 'tmilos' with 'git@github.com:tmilos/test2.git' to git local config.
CMD "git" "config" "--local" "--get" "remote.tmilos.url"
CMD "git" "config" "--local" "--get" "remote.tmilos.url"
CMD "git" "config" "remote.tmilos.url" "https://github.com/tmilos/test2.git" "--local"
CMD "git" "config" "--local" "--get" "remote.tmilos.pushurl"
CMD "git" "config" "remote.tmilos.pushurl" "git@github.com:tmilos/test2.git" "--local"
CMD "git" "rev-parse" "--abbrev-ref" "HEAD"
CMD "git" "status" "--porcelain" "--untracked-files=no"
CMD "git" "rev-parse" "--abbrev-ref" "HEAD"
CMD "git" "rev-parse" "--abbrev-ref" "HEAD"
CMD "git" "remote" "update" "aerialship"
CMD "git" "reset" "--hard" "HEAD~1"
CMD "git" "pull" "-u" "aerialship" "master"
CMD "git" "remote" "update" "tmilos"
CMD "git" "checkout" "tmilos/aaa"
CMD "git" "checkout" "-b" "tmp--tmilos--aaa"
CMD "git" "status" "--porcelain" "--untracked-files=no"
CMD "git" "rev-parse" "--abbrev-ref" "HEAD"
CMD "git" "checkout" "tmp--tmilos--aaa"
CMD "git" "--no-pager" "log" "--oneline" "--no-color" "--format=%ae" "master..tmp--tmilos--aaa"
CMD "git" "--no-pager" "log" "--oneline" "--no-color" "--format=%H" "--reverse" "master..tmp--tmilos--aaa"
CMD "git" "--no-pager" "show" "--format=%an <%ae>%n%s%n%n%b" "--no-color" "--no-patch" "18f256d70ee042fbd2faf3833ce37ae6c3495710"
CMD "git" "reset" "--soft" "master"
CMD "git" "commit" "-F" "C:\Users\mtomic\AppData\Local\Temp\gush\1931.tmp" "-a" "--author" "Milos Tomic <tmilos@gmail.com>"
CMD "git" "--no-pager" "log" "--oneline" "--no-color" "--format=%H" "--reverse" "master..tmp--tmilos--aaa"
CMD "git" "--no-pager" "show" "--format=%an <%ae>%n%s%n%b" "--no-color" "--no-patch" "271ce298200379a594a08c7d97d3449351972cab"
CMD "git" "status" "--porcelain" "--untracked-files=no"
CMD "git" "rev-parse" "--abbrev-ref" "HEAD"
CMD "git" "checkout" "master"
CMD "git" "merge" "--no-ff" "--no-commit" "tmp--tmilos--aaa"
OUT Removing foo.md
Removing bar.md
OUT Automatic merge went well; stopped before committing as requested
CMD "git" "commit" "-F" "C:\Users\mtomic\AppData\Local\Temp\gush\1B5E.tmp"
OUT [master bf24526] merge #3 Aaa (tmilos)
CMD "git" "rev-parse" "HEAD"
CMD "git" "push" "aerialship" "master"
This PR was squashed before being merged into the master branch (closes #3).
CMD "git" "branch" "-D" "tmp--tmilos--aaa"

D:\www\home\aerial\test2>
```

Hope this will give you enough info to reproduce and solve it.

**Comment by sstok** [comment]
That definitely helps, now we can reproduce the situation, I wonder the if issue is caused by the `"git" "reset" "--hard" "HEAD~1"`?

It seems somehow git just uses the tmp--tmilos--aaa as new head, and ignoring everything that is missing in between :confused: I will look into this asap.

**Comment by cordoval** [comment]
btw @sstok on the output of commands we should implode all into one string so the output is rid of the ```"``` (quotes everywhere).

**Comment by sstok** [comment]
Actually those quotes allow to run the command directly :) if you do a quick copy-past you shouldn't have to worry about escaping. And it also helps with debugging, what you see is what was executed.

**Comment by sstok** [comment]
@cordoval Do you agree with rewriting `GitHelper::syncWithRemote()` to use git rebase instead of doing a git reset --hard? Its what I always use.

As an alternative is to use create a temp-branch based on the `org/base`, merge into that one and then push with the temp branch? (this something we do already, but syncWithRemote seems bit magic to me as its not clears whats happening in all situations).

**Comment by cordoval** [comment]
I love rebase but not on syncing a branch that must be synced in all cases in a strong way.
I can't recall right now the use case but there are cases where rebase just does not cut it. In reality i would also have to rely on reset --hard HEAD~n where n is greater than e.g. 10 or 20 for confidence i actually get the right branch with the same status and sha1 as upstream. This is very important, there shouldn't be room for error and also rebase unfortunately does not warrant absolute syncing because a lot of things can go wrong, plus rebase will put extra commits not on branch upstream. Rebase produces cases when conflicts need to be resolved, whereas a true reset warrants you get the same exact thing. Though the only problem is how much you go back without also producing errors because the repository can have just 1 commit or such. This latter case is very unlikely and also you don't want a big number unnecessarily. This is why i have 1, more than that could suit but it is less likely and that requires probably a closer examination. The most common case is the reset of a merge which makes here total sense. Maybe it must be exactly 1 depending on the context in which is written long ago :older_man:. I hope I have warmed your heart and convinced you of my git foo :wine_glass:

**Comment by cordoval** [comment]
@tmilos @sstok should we keep this issue open or it is not really a problem anymore?

**Comment by cordoval** [comment]
now that i reread the thread, i believe i have a hint where the problem is happening. This is not on the reset but as @tmilos is saying this happens because of the squashing with an old base. It will need either an updated local branch and also a mindful rebase -i that is happening on the squash i believe. The reset is ok @sstok unless we need to for sure reset it further like -10 or so. Hmm but i think we are narrowing on the issue after all.

**Comment by sstok** [comment]
OK I will keep that one then ;) for the merging we can use my second idea because it ensures a clean merge and not were you have some work in the master branch forgot to push this and then wondering why were those other commits came from :) I will get working on that :-1:

**Comment by sstok** [comment]
I'm taking on this one, I finally understand whats happening (and its hard to understand :scream: ).

Your local base is outdated, you add new commits and then push that branch to the remote.
The remote has your outdated base commits, PLUS additional commits that were added later.

When you push your branch Git will have to figure out how to apply your commits, and thats were allot of mathmagic happens and things go wrong. For some reason Git applies the diff of the old base on top of the new base, undoing the all the changes that have happened.

The way to ensure this always works, is to always merge into an up-to-date base branch.

@tmilos Sorry it had to take this long, we finally know whats going wrong and I'm going to fix this today!

**Comment by cordoval** [comment]
thanks @sstok great job

@tmilos :+1: LGTM
