### ISSUE TITLE
Don't require "gush.yml" for "core:update" command

### ISSUE THREAD

**Issue by aik099** [gushphp/gush#374]
I've installed `gush.phar` in `/usr/local/bin` folder as `root`. Then I'm running `php /usr/local/bin/gush.phar core:update` and getting an exception that `gush.yml` is missing. And that's true: the `root` user doesn't have it and it shouldn't.

For now please don't require `gush.yml` for `core:update` command. But ideally each command should say whatever it needs `gush.yml` or not.

**Comment by cordoval** [comment]
closed via #381
