### ISSUE TITLE
Breaking the circular dependency between adapters and the gush package

### ISSUE THREAD

**Issue by sstok** [gushphp/gush#380]
Currently all the adapters have a dependency on the `gushphp/gush`, but `gushphp/gush` requires all the adapters, which causes a circular dependency between the packages. Making changes in the interface a real "challenge".

The original idea was to fix this is using a composer plugin, but this would only solve one problem.
Because the `gushphp/gush` package still requires all the adapters :angry:

Also we don't actually use plugins or external adapters like bldr does, using the phar is the only supported method.

Since the https://github.com/gushphp/gush/blob/master/bin/gush will only enable adapters that are installed, we don't actually need the adapters to make gush work, we only need them for the phar building process.

So here are some options I think of:

1. use a dedicated composer.json for the phar building (if at all possible)
2. move adapters to the `require-dev` section; this will however also install the dev-tools which is not what we want.
3. Create a new repository named `gush-application` which contains the phar-builder, a composer.json for installing `gushphp/gush` and the adapters. The original package does no longer require the adapters.

Better ideas and suggestions are welcome :+1:

**Comment by cordoval** [comment]
repos removed :+1: 

I think we should ask @matthiasnoback about this.

I personally like 1, since bldr (@aquaesi tool) can do this without problems ?

**Comment by cordoval** [comment]
great team work @sstok :open_hands: :ok_hand:

**Comment by sstok** [comment]
I discovered something :flushed: the reason why adding "gushphp/gush" as dev-requirement for some adapters doesn't work is because the branch-alias is missing in those adapter packages!

If we are working on an adapter simply add the branch-name as branch-alias and gush should have no problem being installed as an dependency :smile: Why did I not discover this sooner :hammer: 

```
"extra": {
        "branch-alias": {
            "dev-master": "1.11-dev"
            "dev-my-new-feature": "1.12-dev"
        }
    }
```

**Comment by sstok** [comment]
When add `gushphp/gush` as (dev-)requirement to say the `gushphp/gush-github-adapter` and install the deps for that package the `gushphp/gush` requires the `gushphp/gush-github-adapter` package which is provided by the current package.

BUT! The `gushphp/gush-github-adapter` package has no branch-alias so Composer will use the branch-name (master) as the provided version `dev-master` which does not fulfill the version-requirement for the `gushphp/gush-github-adapter` which is `~1.10`. And so Composer gives-up.

But if you add a branch alias to `gushphp/gush-github-adapter` composer will known that master is the same as `1.11.0` fulfills the requirement.

Alternatively you set the `COMPOSER_ROOT_VERSION` env variable to `1.11.0` as its works the same as the branch-alias for the root-package (the one you are running the composer command with now).

**Comment by sstok** [comment]
I tried it and its working :+1:
