### ISSUE TITLE
git-sweep like functionality

### ISSUE THREAD

**Issue by cordoval** [gushphp/gush#382]
from #18 we extract this one. Basically a way to locally and remotely to clean up merged branches. bookkeeping and stuff.

**Comment by cordoval** [comment]
cc @sstok comments?

**Comment by sstok** [comment]
Indeed, I always have to git remote prune for all remotes. So I'm :+1: for this

**Comment by cordoval** [comment]
now you see how i look on my avatar :baby: :+1: i will try to aim at this issue tonight when all is quiet. I hope you have a good sunday!

**Comment by sstok** [comment]
OK ;)

**Comment by sstok** [comment]
`git branch --merged master | grep -v 'master$' | xargs git branch -d`
This will remove all branches that are merged in the master.

Source: http://lukas.zapletalovi.com/2012/07/my-git-aliases-again.html

**Comment by cordoval** [comment]
i guess this goes also in the vein for removing branches pushed to remote perhaps too, though that should be a flag or separate command #499

**Comment by cordoval** [comment]
This is still in my heart :blush:

**Comment by cordoval** [comment]
too intrusive
