### ISSUE TITLE
checkout command

### ISSUE THREAD

**Issue by cordoval** [gushphp/gush#384]
one of the things i think gush has been missing is this https://github.com/github/hub/blob/master/commands/checkout.go

```go
/**
  $ gh checkout https://github.com/jingweno/gh/pull/73
  > git remote add -f -t feature git://github:com/foo/gh.git
  > git checkout --track -B foo-feature foo/feature
  $ gh checkout https://github.com/jingweno/gh/pull/73 custom-branch-name
**/
```
we can do a better job than that which a more clearer architecture perhaps and maybe open for more, what sayest @sstok ? we would like it to assume github or respective adapter

**Comment by sstok** [comment]
:+1:

**Comment by cordoval** [comment]
indeed the same go is doing is implementing callbacks or closures for their commands. I think Gush can go this route so it will leave open for more customization.
