### ISSUE TITLE
error on github CRITICAL

### ISSUE THREAD

**Issue by cordoval** [gushphp/gush#387]
```
gush -v release:list
```
https://cloudup.com/cvsx9UkCEyk and 

```
git remote -v
```
https://cloudup.com/cPp0nxbTG0X
trying to help this nice guy on #qandidate channel

**Comment by nWidart** [comment]
Thank you :smiley: 

This happens for every command, like `issue:list` and so on.

**Comment by sstok** [comment]
I'm not sure what is causing this, but it seems the wrong username is resolved somehow.
The `getVendorName()` name is used for determining the user/vendor but its very fragile, I'm currently rewriting it be more robust.

**Comment by sstok** [comment]
@nWidart can try #388 and see if this solves the problem?

**Comment by nWidart** [comment]
Issue still present.

**Comment by sstok** [comment]
Can you run the command with the following env set `export GITHUB_DEBUG=true`.
**WARNING! This will also contain the OAUTH token so be careful to remove that when copying the output!!**

**Comment by nWidart** [comment]
```
# Request:
GET /repos/nWidart/Broadway-laravel/issues?page=1&creator&assignee&mentioned&milestone&per_page=100 HTTP/1.1
Host: api.github.com
Accept: application/vnd.github.v3+json
User-Agent: php-github-api (http://github.com/KnpLabs/php-github-api)
Authorization: Basic *********************



# Response:
HTTP/1.1 404 Not Found
Server: GitHub.com
Date: Thu, 29 Jan 2015 13:47:49 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 77
Status: 404 Not Found
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4945
X-RateLimit-Reset: 1422540226
X-GitHub-Media-Type: github.v3; format=json
X-XSS-Protection: 1; mode=block
X-Frame-Options: deny
Content-Security-Policy: default-src 'none'
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Allow-Origin: *
X-GitHub-Request-Id: *******************************
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Content-Type-Options: nosniff

{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}

# Errors: 0
```

**Comment by sstok** [comment]
This is your repository: https://github.com/nWidart/Laravel-broadway
And this is the remote you are currently using: `git@github.com:nWidart/Laravel-broadway.git`

<img src="https://cldup.com/A4nrBpF-GG-3000x3000.png" alt="remote"/>

You went Yoda on the Repository name :wink: update the git remote origin and it should work.

**Comment by cordoval** [comment]
:+1: good catch he he

i am impressed what sort of thing you clone then ... :baby:

**Comment by cordoval** [comment]
please @nWidart reopen if that is not the problem. All should be good now though. And feel free to open if you run into anything else.

**Comment by nWidart** [comment]
Everything works as expected now. Thank you and sorry for the confusion. :) Funny how github managed to pull/push.

I'd like to remove the debug info though, I've set `export GITHUB_DEBUG=false` but still getting the info.

**Comment by cordoval** [comment]
hmm just set GITHUB_DEBUG=true then, weird that it clamped

**Comment by nWidart** [comment]
Re opening that tab did the trick. Thanks again! :smiley:

**Comment by sstok** [comment]
`unset GITHUB_DEBUG` ;)

**Comment by nWidart** [comment]
Ah! Thanks :)
