### ISSUE TITLE
Make pull-reqest merge-type require-able 

### ISSUE THREAD

**Issue by sstok** [gushphp/gush#389]
Add an new option `pr-types: [feature, bug, minor, security]` which will when present, ask the merger what type the PR is.

This will make gush similar to the GH tool. But with more flexibility as this can be configured and is disabled by default. The mean reason for this is to prevents typo's or forgetting to provide a type :smile:  :+1:

**Comment by cordoval** [comment]
to make the command smarter i see

**Comment by cordoval** [comment]
addressed in #394

**Comment by cordoval** [comment]
yey now Gush has PR type feature! :dancers:
