### ISSUE TITLE
hhvm fix tests

### ISSUE THREAD

**Issue by cordoval** [gushphp/gush#397]

**Comment by cordoval** [comment]
i persisted the locks for bldr and composer and now the error is more clear:

https://travis-ci.org/gushphp/gush/jobs/55496176  cc @sstok 

regarding the need for persisting the locks I opened a ticket in https://github.com/composer/composer/issues/3864

**Comment by cordoval** [comment]
they are still failing @sstok :credit_card:

**Comment by sstok** [comment]
Its a bug in HHVM https://github.com/facebook/hhvm/issues/4810 we can't fix this :(

**Comment by cordoval** [comment]
let's turn off then hhvm for good I think is best :sob:

**Comment by sstok** [comment]
allow failure :+1:

**Comment by cordoval** [comment]
there ya gaw :+1:

**Comment by sstok** [comment]
done in 079938764153eb9e928a8f9c06ba0c70c8c23741

**Comment by cordoval** [comment]
gracias mi amigo @sstok
