### ISSUE TITLE
Pull-merge ask confirmation

### ISSUE THREAD

**Issue by sstok** [gushphp/gush#400]
I have little idea for the pull-request:merge command: Ask for confirmation with information about the pull request.

When you merge a pull request the following is possible:

* id given (no extra option): `You are about to merge pull request #{{ id }} - "{{ title }}" into {{ base }}, do you confirm?`
* id given (switch base): `You are about to merge pull request #{{ id }} - "{{ title }}" into {{ new_base }} (instead of {{ base }}), do you confirm?`
* id given (squash): `You are about to merge pull request #{{ id }} - "{{ title }}" (squashed) into {{ base }}, do you confirm?`

When you want to squash while there are multiple authors, the command will ask you if you want to continue or abort.

When `--no-interactive` is given no questions are asked.

**Comment by cordoval** [comment]
i like it but i think it would make the command too complex already? i was just curious if we can avoid this, but feel free. I also would complain that when i run this command i am almost sure what i am doing as this messes with real PRs merged and such. But yeah if it makes sense :+1: but if you are not sure then :-1:

**Comment by sstok** [comment]
I actually think its possible to make this very simple, just add method that handles the interaction.
When its not confirmed the command ends with a user-exception.

**Comment by cordoval** [comment]
I am actually now :+1: because I see you are actually making gush a lot better to be used for FOSS so I am all :+1:

**Comment by cordoval** [comment]
if this is just because of the authors i am :-1: maybe, the problem i am seeing is we need to prompt the least amount of times, already to merge it prompts you like 2 times or something.

**Comment by sstok** [comment]
I usually type `gh p:m pr-number type` so the prompt is not shown ;)
I'm OK with closing this.
