### ISSUE TITLE
style bug or not?

### ISSUE THREAD

**Issue by cordoval** [gushphp/gush#403]
![screen shot 2015-04-08 at 11 11 07 am](https://cloud.githubusercontent.com/assets/328359/7049551/13e27e28-dde0-11e4-960a-42b3e9dacdf0.png)

**Comment by sstok** [comment]
Its a problem with Symfony (when using a small terminal screen), but this should have been fixed already :confused:

**Comment by cordoval** [comment]
this is the commit in symfony right https://github.com/symfony/symfony/pull/14136 do we have it though? we are on 2.7@dev hmm

**Comment by cordoval** [comment]
I think this is on and off happening for some commands and for some others it does not happen ....

**Comment by cordoval** [comment]
closing for now until it becomes a major hurdle
