### ISSUE TITLE
Command to update pull-request with base `pull-request:sync-base`

### ISSUE THREAD

**Issue by sstok** [gushphp/gush#410]
One of the most asked questions to contributers is `Could you rebase before I merge`.
But not everyone (no offense ;) ) don't always get this right as they push but without `--force` or they use the wrong base.

Or what I did once, do a push with force but then realize you forgot to include the branch name (so all the branches get overwritten :clap: :neutral_face: *and that was not a fork...* )

To make this easier we can add a new command `pull-request:sync-base pull_id`, which uses the information of the pull-request for getting the right base, remote (source-org) and doing the push safely.

Plus you can do a fast `pull-request:sync-base 105` and after this continue with the original branch (which is checked out afterwards).

## Rebase conflict resolving

When rebasing you have the risk of getting a conflict, instead of working around this the command will simply fail and the user needs handle the conflict using git itself.

```
[error] Could not complete the pull-request:sync-base command.

Git rebase failed, you need to resolve these problems manually.

Once you have resolved all the rebase problems , run the pull-request:sync-base command
without any arguments and the sync operation should continue without any errors.

To resolve these problems [nice detailed description here]

To check out the original branch and stop syncing, run "gush pull-request:sync-base --abort".
```

To help the user, Gush will remember that the user was in a sync-base operation, so running `pull-request:sync-base` again will automatically get the correct pull-id or warn when running another command (same way git handles rebase in progress errors).

And restore the orginal branch after the operation is fully completed or the user aborted.

Rebase completed, sync not completed: 

```
You were doing a pull-request sync-base operation, do you want to continue the original sync operation? [Yes/no]
```

No means the sync operation is aborted, the pull-request branch is left unchanged (no git reset).

Rebase not completed:

```
You were doing a pull-request sync-base operation, but git rebase is not completed yet.

Once you have resolved all the rebase errors, run the pull-request:sync-base command
without any arguments and the sync operation should continue without any errors.

To resolve these problems [nice detailed description here]

To check out the original branch and stop syncing, run "gush pull-request:sync-base --abort".
```

## Internal notes

To make the implementation not to complicated the error message and command-name with arguments is written to `.git/.gush_operation` (as a YAML file), the Application simply checks if there is `.git/.gush_operation` file and uses that information for replacing the current command (in doRunCommand(). don't worry I have some idea's to rewrite that method ;) ).

And a another addition is to remember the original (the stashed brach-name) in a `.git/gush_orig_branch` to make aborting a command not loose the original branch-name.
Just an idea, so not fully sure on this as it only works for Gush commands.

**Comment by cordoval** [comment]
hmm not sure i am fully understanding or convinced, but we can discuss on our conversations.

**Comment by cordoval** [comment]
i think this is a duplicate?

**Comment by sstok** [comment]
Duplicate of what? :) the sync command updates your local branch with the remote version.
But pull-request:sync-base will rebase your local branch with the remote base.

In practice it does this:

```bash
git fetch [upstream-remote]
git checkout [your-pull-request-branch]
git rebase [upstream-remote]/[base]
git push -f [your-remote] [your-pull-request-branch]
```

Thinking about this now :) I Think it's possible to do this today without to much issues.
Simple try to do the rebase and if it fails, abort and show the instructions on screen! :+1: 

It's more about educating then any special kind of logic.

**Comment by sstok** [comment]
Closing this, you can safely use git rebase and gush branch:push --force but risk of a failure is to big and fixing requires to much logic on our side.
