### ISSUE TITLE
[RFC] pull-reques:create remove --issue option

### ISSUE THREAD

**Issue by sstok** [gushphp/gush#418]
The `--issue` only works for GitHub and I don't really see it being used that often (anymore), and to me it also feels a bit strange to replace an existing issue with a PR keeping all the original comments :smile: 

I already asked to remove this in #166 but @cordoval said to use it :)
@gushphp/contributor what do you think about removing this option?

I don't have problem with keeping this option, but pull-request:create needs to be rewritten as the complexity is way to high: https://scrutinizer-ci.com/g/gushphp/gush/code-structure/master/operation/Gush%5CCommand%5CPullRequest%5CPullRequestCreateCommand%3A%3Aexecute

**Comment by cordoval** [comment]
let's remove it :+1: i have been working and this is not needed anymore as @stof posed a good case for when you don't need to turn issues into PRs, is better to just launch them independently

**Comment by sstok** [comment]
See #419
