### ISSUE TITLE
weird problems on gitlab

### ISSUE THREAD

**Issue by cordoval** [gushphp/gush#421]
https://github.com/gushphp/gush-gitlab-adapter/issues/11

```
✗ gush issue:create
Issue title: fix default postgres parameters

  [Gitlab\Exception\ErrorException]    
  400 (Bad request) "title" not given
```

```
✗ gush p:create --source-branch="docker-setup"
Title: [created working docker setup (via fig)]
Notes (:+1:) 
Description (enter "e" to open editor) 

  [Gitlab\Exception\ErrorException]            
  400 (Bad request) "source_branch" not given
```

so, even if i manually set required parameters - it tells me they are not set. Please let me know if you need more information about environment or anything else.

reported initially by @AlexKovalevych

**Comment by cordoval** [comment]
@AlexKovalevych i just tested this on the new branch on gush that moves the adapters into the core repo and couldn't reproduce. Can you check if you can still reproduce this in that branch? Thanks

**Comment by cordoval** [comment]
ping @AlexKovalevych ?

**Comment by AlexKovalevych** [comment]
Yup, i'll try it today a bit later

**Comment by AlexKovalevych** [comment]
Confirm - creating issue doesn't work in the latest gush. A gitlab library looks weird, i never used it before, but for example python library sends a json request when creating an issue (https://github.com/gpocentek/python-gitlab/blob/master/gitlab/__init__.py#L454), php library - sends parameters in the query string. i'll investigate it deeper on the weekend.

**Comment by cordoval** [comment]
@AlexKovalevych did you investigate it?

**Comment by cordoval** [comment]
solved it on master
