### ISSUE TITLE
[WIP] Application refactoring roadmap

### ISSUE THREAD

**Issue by sstok** [gushphp/gush#427]
Related to #401 this describes the roadmap to take for refactoring the Application in Gush 2.0.

The final goal is to decouple Gush from any framework or library.
To make this possible the application is designed with the adapter design-pattern whenever possible.

### Commands

* Commands work similar to web Controllers, they are thin and function as a layer between the Console Application and underlying services.

* Commands only communicate with an "API Adapter" or "Service" and never with any other system directly. So instead of running the php-cs-fixer executable directly this happens through a Service like "CsFixer" which invokes the php-cs-fixer and handles any output back to the Command.

* ~~System (Git commands) are always done using the GitSystem service (better name needed), complex operations like merging or rebasing are done using an Operation, the Command only configures the operator for execution.~~ (Done using the GitHelper)

* Commands are decoupled from any 3rd part library.

* Command handling is separated from the command definition (the command definition is an implementation detail of the used library).

* We use our own IO interface instead of relying on the Console libraries implementation.
  * This handles all IO operations, including questions and table rendering.
  * The current StyleHelper will be moved to this interface.

### Service layer

TBD.

**Comment by cordoval** [comment]
this ticket must be broken down into actionables

**Comment by sstok** [comment]
I will work on some of the idea's and issues in the weekend ;)
Most of this is already done, I'm horrible at keeping my notes up-to-date :)
