### ISSUE TITLE
Cannot open pull-request when base is not existing as local branch

### ISSUE THREAD

**Issue by sstok** [gushphp/gush#436]
```
[RuntimeException]
fatal: No such ref: '1.x'
```

Should use the base of the org `org-name/base-name` for fork-point, which also prevents getting the wrong default title :smile:

**Comment by cordoval** [comment]
not sure if i understand the full scenario for this

**Comment by sstok** [comment]
If you open a pull-request (without the --title option) Gush will try to guess the Title by getting the first commit of the source branch. To make this possible it needs an existing base branch (the base is used as a real branch, so if its not checked out with an actual name you get a fatal error).

If you take an issue with a different base (which is not checked out already) and then later open a new pull-request the base used for taking is none existent.

In this case the 1.0 branch was renamed to 1.x (remotely), but I did not rename it locally yet, so Git failed with a fatal error.
