### ISSUE TITLE
upper case first letter of title in PR

### ISSUE THREAD

**Issue by cordoval** [gushphp/gush#437]
i think people like it, i know i never upper case commit messages but maybe it looks more elegant after all

**Comment by sstok** [comment]
You mean the merge message? I followed the Symfony casing :)

I actually want (when time comes) add a bit more flexibility in how the merge message is rendered, but not using the current template System, but more something like Twig (only lighter, as Twig is a little to big :smiley: but maybe we strip Twig down to what we need).

**Comment by cordoval** [comment]
I think the default title is set from the first commit message, however if this commit message starts with lower case then it will not upper case the first letter of the phrase/sentence by default which i think would be desirable.

**Comment by sstok** [comment]
:+1:

**Comment by cordoval** [comment]
addressed in #507

**Comment by cordoval** [comment]
@GrahamCampbell there must be some setting on git to also ucfirst the individual commit messages, do you know? or anyone else? :blush:

**Comment by sstok** [comment]
It is possible to force a specific format of the commit message
https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks

> The commit-msg hook takes one parameter, which again is the path to a temporary file that contains the commit message written by the developer. If this script exits non-zero, Git aborts the commit process, so you can use it to validate your project state or commit message before allowing a commit to go through. In the last section of this chapter, We’ll demonstrate using this hook to check that your commit message is conformant to a required pattern.

You can (ab)use this to change the commit message but I'm not sure if this will also fire for a merge.
http://stackoverflow.com/a/5824876

Also you need to apply this hook locally, meaning very one of the developers/contributers need to install this.
