### ISSUE TITLE
More unique remote-name

### ISSUE THREAD

**Issue by sstok** [gushphp/gush#438]
Currently the remote-name is based on the organization name, but nothing prevents you from having the same repository twice within the same organization.

`gushphp/gush` and `gushphp/gush-private` both use the same remote-name but point a different url!
If you need to move a pull-request from a READ-only repository this will get you into trouble.

To be fully unique the remote-name should be based on the org AND repo plus the adapter-name like: `gushphp_gush_github` or when using enterprise `gushphp_gush_github_[on_hostname]`.

This shouldn't not a problem for existing users as the name is automatically registered :)

**Comment by cordoval** [comment]
hmm not sure i understand the scenario of this, a bit confusing

**Comment by sstok** [comment]
If you want move a pull-request/issue or branch within the same org (not the same repository) Gush will fail as it only uses the org-name for remote-name.

**Comment by cordoval** [comment]
assume there is also a need to move all issue tickets from repoA to repoB as well. :clap:

**Comment by cordoval** [comment]
I just reread this and I am not sure is a common case. I am against complicating things just for this edge case. The most typical scenario is you develop on one repo and clone/fork for an organization. There is a central repo. Git is based on distributed versioning, but having the same repository under different name in the same organization sounds too ad-hoc.
