### ISSUE TITLE
not setting upstream by default

### ISSUE THREAD

**Issue by cordoval** [gushphp/gush#439]
```bash
~ git push                                                Luiss-iMac [15:44:36]
fatal: The current branch 1576-css-print-styling has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin 1576-css-print-styling
```

This happens even after sending a PR with gush, this just does not set it up like before

**Comment by sstok** [comment]
The pushing of the branch wasn't done before #408 but it set set to an upstream, so that should work.

The `branch:push` command however doesn't automatically set the upstream unless you provide `--set-upstream`.

**Comment by cordoval** [comment]
#408 is from April, and I think i get this error after. So gush p:create is not setting it up correctly. I think the branch:push should set the upstream by default perhaps? or via at least by configuration on .gush.yml?

**Comment by cordoval** [comment]
is this still valid after knowing that i can set the upstream with -u cordoval cc @sstok ?

**Comment by sstok** [comment]
Nope, this can be closed :)
