### ISSUE TITLE
Automatically load puttykeyfile for Windows users

### ISSUE THREAD

**Issue by sstok** [gushphp/gush#441]
As a Windows user I use TortoiseGit for doing must of me Git stuff :) and one handy feature this provides is to automatically load a putty key file whenever I connect. When I use Gush however I first need to load my key file before the connection can work.

Loading the file is as simple as `"C:\Program Files\TortoiseGit\bin\pageant.exe" "Path to ppk file"`.
So as a feature for Windows users we can allow to automatically load the ppk file when this is configured.

Note. The GIT_SSH must be set to plink.exe and not the native ssh.exe client!

**Comment by cordoval** [comment]
hmm interesting, I wonder if this can be approached via ~/.ssh/config file rather than doing these things in gush

**Comment by sstok** [comment]
Indeed, I only use Pagent because doesn't require to fill in the password ever time.
Using the SSH Agent on Windows is also possible, but it requires a bit more work :) 

Just found https://help.github.com/articles/working-with-ssh-key-passphrases/#platform-windows will look if I can get that to work as a replacement.

**Comment by sstok** [comment]
Works perfect with the SSH agent :+1: can I close this then :)

**Comment by cordoval** [comment]
nice find!
