### ISSUE TITLE
gush b:f is broken for arbitrary repos

### ISSUE THREAD

**Issue by cordoval** [gushphp/gush#443]
```bash
~ gush b:f                                         Luiss-MacBook-Pro [20:32:35]



  [Github\Exception\ValidationFailedException]
  Validation Failed: Field "organization" is invalid, for resource "Fork"
```

It seems to me that when the fork is already there it fails. I think it should just attempt to do it again and give no error.

**Comment by cordoval** [comment]
you explained at some point the real reason for these types of failure, can you please state that here cc @sstok ?

**Comment by sstok** [comment]
This is because when you fork a repository to your own organization (profile) the GitHub adapter will fail. It should be fixed already.

**Comment by cordoval** [comment]
we probably need to tag and bump things up right? because composer install will not update to latest versions if there is a lock already

**Comment by sstok** [comment]
Yes, the fix was done on https://github.com/gushphp/gush-github-adapter/commit/0116b38e6522800a74efea8bb8e8f3b58c893507 and the last tag was from Dec 2014

**Comment by cordoval** [comment]
tagged including the fix now https://github.com/gushphp/gush-github-adapter/releases/tag/1.1.11
