### ISSUE TITLE
consecutive PRs stash somehow previous title/commit

### ISSUE THREAD

**Issue by cordoval** [gushphp/gush#448]
when doing PRs by default instead of taking the title of the commit it is taking the previous PR from another branch and stuff, very weird, i am surprised

**Comment by sstok** [comment]
Could be related to #436 make sure the local base branch is up-to-date.

**Comment by cordoval** [comment]
but even if it is not up to date because is a fast moving repo, i wonder if we can prevent this no?

**Comment by sstok** [comment]
#449
