### ISSUE TITLE
Syntax error in manifest.json

### ISSUE THREAD

**Issue by pierredup** [gushphp/gush#456]
I can't update gush using `gush core:update`, because the http://gushphp.org/manifest.json file has a syntax error (`,` needed after the sha1)

![screen shot 2015-06-04 at 16 02 09](https://cloud.githubusercontent.com/assets/144858/7985738/428db59c-0ad3-11e5-9e32-9972465895a7.png)

**Comment by cordoval** [comment]
good catch, my fault will fix now

**Comment by cordoval** [comment]
done, thanks @pierredup for giving a shout about this :+1: :older_man:

**Comment by pierredup** [comment]
I'm now getting the following, but not sure if it's something to do with my local environment or something else

![screen shot 2015-06-04 at 16 17 34](https://cloud.githubusercontent.com/assets/144858/7986037/5666a978-0ad5-11e5-9f0a-85f771385ff7.png)

**Comment by cordoval** [comment]
i will take a look

**Comment by sstok** [comment]
There is no TLS connection possible, gushphp.org has no cert or such.

**Comment by cordoval** [comment]
hmm i wonder what to do in this case, i thought we had it so that the connection was not SSL in this case, until someone generous can get us a certificate. ..

**Comment by pierredup** [comment]
Maybe change the url in the manifest.json to `http://gushphp.org/gush.phar` (without https) so that the update can work

**Comment by cordoval** [comment]
perhaps this can help @pierredup https://github.com/gushphp/installer

i will fetch from there to deploy from now on
