### ISSUE TITLE
Make `repo:fork` create a new local repository if not in a git repository

### ISSUE THREAD

**Issue by sstok** [gushphp/gush#459]
Say I want to contribute a project (like Symfony), now I must first fork and create a local git repository.

But instead we should be able to just execute: `gush branch:fork symfony symfony` which forks the Symfony repository to my account, then executes `git clone URL`. And also execute gush core:init (in the background).

Edit. Minor correction :)

**Comment by cordoval** [comment]
:+1:

**Comment by webflo** [comment]
:+1:  i use ``hub fork`` as workaround for github.

**Comment by sstok** [comment]
Hehe I need to get working on this as I'm already using this recommendation :flushed: :sweat_smile:
https://contributing.readthedocs.org/en/latest/code/patches.html#get-the-project-source-code

**Comment by cordoval** [comment]
your contributing documentation is not associated to any package, but it is better than gush

I wonder if we put this under the gush umbrella, and provide links from gushphp.org

**Comment by cordoval** [comment]
I think this ticket title is wrong. So I will update it to be repo:fork instead of branch:fork

**Comment by cordoval** [comment]
This should work probably assume a generic adapter, will do filesystem things then clone the repo and that is it.

**Comment by sstok** [comment]
Instead of changing this command I'm in favor for a new command `repo:clone` because it's more a clone then a fork. Just simple check if there is already a fork, and ask to create one when it doesn't exist.

**Comment by sstok** [comment]
Using the web portal is much faster. 

When this happens outside of a git repository you also need to provide which adapter.
You can simple git clone the repository, and use gush repo:fork when you are in the repository, or use gush branch:remote:add. 

Closing this one.
