### ISSUE TITLE
Encrypting the configuration (passwords and tokens)

### ISSUE THREAD

**Issue by sstok** [gushphp/gush#470]
Currently the Gush configuration (passwords and tokens) are stored in plain-text!
From a security point-of-view this is horribly insecure.

Passwords and tokens should (*must*) be stored encrypted using a master-password.
But then you would need to provide a password every time you use Gush!

The first solution that came to mind was a configuration-agent (like the ssh-agent)! When you start Gush, an agent will be started (if not already running) which keeps the passwords and tokens decrypted in memory. So you only have to provide the master-password once per session.

There is already a very good library to do the encryption safely: https://github.com/defuse/php-encryption 

*Personally I would like to use https://github.com/jedisct1/libsodium-php as it also provides memory clearing (removing traces from memory) but this requires that extension is installed, so this should only be used as a recommendation and considered 'upgraded security'.*

Some things I wonder about:

* Should we encrypt the whole file or only the authentication info?
* Its recommended (by defuse) to not use passwords but use a key derived from the password, but as this configuration is only local should this be applied?
* Is memory clearing really mandatory? I know it improves security, but what is the actual risk of not doing this.

@ircmaxell as a security expert of the open-source community do you have any other suggestions or comments on this idea? :+1:

**Comment by cordoval** [comment]
I like the idea of a passphrase to secure ssh private key like behavior for gush

**Comment by sstok** [comment]
From his Twitter feed it seems Anthony is on a vacation :) I will ping him again when he gets back.

**Comment by cordoval** [comment]
there are other experts that can advise too @enygma or ... well i don't know many :blush:

**Comment by sstok** [comment]
I know `@padraic (Pádraic Brady), @defuse (Taylor Hornby) creator of the php-encryption library, and @paragonie-scott (Scott)` :+1:

**Comment by cordoval** [comment]
@ircmaxell, i know you are very busy and probably you care little about this project, but if we can still get some kind of response from you would be great to have some closure on this. Thanks in advance.

**Comment by ircmaxell** [comment]
Why not just use the systems keychain (on OSX: http://blog.macromates.com/2006/keychain-access-from-shell/ on Linux: http://askubuntu.com/questions/262698/how-do-i-get-passwords-from-the-keyring-in-the-terminal-for-usage-in-scripts etc).

Basically, generate an encryption key, store it in the system's keychain, then encrypt the config file (the whole thing) with that key. You should create a second config file (or wrapper) which contains the keychain info.

Then simply decrypt and move on.

Creating your own agent is going to be problematic (though it is an interesting proposition).

Also, as an aside, the documentation really never says clearly what this project does. I had a very hard time figuring out *why* you need all of those credentials...

**Comment by sstok** [comment]
Thanks for the heads-up and information.

> Also, as an aside, the documentation really never says clearly what this project does. I had a very hard time figuring out why you need all of those credentials...

We communicate with the GitHub API (and others) to open/close/modify issues/pull-requests and manage branches.

*The (old) configurator actually allowed to use a username/password and store this in plain text! The new one always generates a new token, but it got lost during some version switching (I still got the commit but need to restore it).*

**Comment by cordoval** [comment]
I like @ircmaxell option to just use keychain, but for now i don't think this is as important for development. If I get my laptop stolen I am in big trouble anyways. I believe that is what 2fa is for if you require extra security.

**Comment by sstok** [comment]
OK, it's a bit to much work for now. Lets keep it open If anyone is willing to work on it :+1:

**Comment by cordoval** [comment]
:+1:
