### ISSUE TITLE
StyleCI patch applier

### ISSUE THREAD

**Issue by sstok** [gushphp/gush#473]
Similar to what we have for Fabbot.io but then for StyleCI.io :)

**Comment by GrahamCampbell** [comment]
This would be awesome. :)

**Comment by sstok** [comment]
@GrahamCampbell is there a way to get the patch-url for PR?

Fabbot provides this information with `http://fabbot.io/patch/org/repo/pr-nr/hash/` but styleci hides this behind a shortened URI like https://styleci.io/analyses/qoWlZq/diff

**Comment by GrahamCampbell** [comment]
The way to get the patch url for a pull request would be to use github's api to get the head commit in the PR, then look at the status API to get the analysis url.

**Comment by GrahamCampbell** [comment]
The status API might even let you get the status for a pull request. I'm not sure. You might be able to use `refs/pull/42/head` as a ref, or something simelar.

**Comment by GrahamCampbell** [comment]
> Fabbot provides this information with http://fabbot.io/patch/org/repo/pr-nr/hash/

The trouble is that a single commit hash can have multiple analyses on our system, so it's not a one-to-one mapping.

**Comment by GrahamCampbell** [comment]
Just read your comment again. If you have the sha id, all you need to do it go to github's status API and ask it for the styleci analysis id.

You;re going to want to call:
```
GET /repos/:owner/:repo/commits/:ref/status
```

Then look for the entry where `context` is `StyleCI`.

**Comment by sstok** [comment]
OK will try that :+1:

**Comment by sstok** [comment]
Its here :smile: #474
