### ISSUE TITLE
anyone wants to send a PR including styleCI badge

### ISSUE THREAD

**Issue by cordoval** [gushphp/gush#475]
cc @sstok ?

**Comment by cordoval** [comment]
bump @GrahamCampbell

**Comment by cordoval** [comment]
notice this is separate from the other gushphp site

**Comment by GrahamCampbell** [comment]
![image](https://cloud.githubusercontent.com/assets/11048387/9155008/601d49e0-3ea1-11e5-900b-f6329762f175.png)

**Comment by cordoval** [comment]
addressing in #476
