### ISSUE TITLE
pull-request:squash should use a temp-branch instead of the local branch

### ISSUE THREAD

**Issue by sstok** [gushphp/gush#483]
If the local source branch is not up-to-date the remote branch, the remote commits will be lost!

We however can't simple push to remote and leave the local branch as-is, this would cause hash mismatches and many confusion. So this requires a thorough process.

Always ask confirmation and warn about breakage of tracking branches.
1. Check if there is a local source branch,
   1. If there is a branch look if it's set-up as upstream/tracking.
      x. Check if the local branch is up-to-date. if not, error about this and abort.
      x. If it's up-to-date continue, we still use a temp-branch to easily recover from errors.
   2. If the local branch is not set-up as tracking, continue as normal (local branch is ignored basically).
2. If no local source branch exists, continue using a temp-branch.

**Comment by cordoval** [comment]
i think we could just ask or run before the rebase command or prompt for it.

**Comment by sstok** [comment]
That's the idea ;) I really need to work on these issues of mine ASAP.

**Comment by cordoval** [comment]
you can also just digest them and encourage others to implement send PR then you review, so that we get some input too, maybe @gushphp/contributor knows some tricks that we haven't heard of

**Comment by sstok** [comment]
I may have an idea for when the local branch is not up-to-date, check if a safe rebase is possible (and perform it), if not do a rebase with `--onto` to merge both branches together.

**Comment by sstok** [comment]
https://stackoverflow.com/questions/8716130/git-branches-diverged-how-to-proceed
https://stackoverflow.com/questions/3080509/list-git-commits-not-pushed-to-the-origin-yet
https://gist.github.com/WebPlatformDocs/437f763b948c926ca7ba

**Comment by sstok** [comment]
Taking on this one now 👍
