### ISSUE TITLE
gush styleci badge still red even though it should be green

### ISSUE THREAD

**Issue by cordoval** [gushphp/gush#485]
cc @GrahamCampbell

**Comment by GrahamCampbell** [comment]
Looks like a caching issue with github.

**Comment by GrahamCampbell** [comment]
If you visit https://styleci.io/repos/16789051/shield, you get the correct badge.

**Comment by pierredup** [comment]
It's because StyleCI does not send the correct `Cache-Control` header

**Comment by GrahamCampbell** [comment]
> It's because StyleCI does not send the correct Cache-Control header

It's not us that send that header. It's shields.io.

**Comment by GrahamCampbell** [comment]
I'm considering ditching shields.io and just serving the badges our selves.

**Comment by GrahamCampbell** [comment]
And, actually, we do send the correct Cache-Control header: https://i.starbs.net/7vLo.

**Comment by GrahamCampbell** [comment]
This defiently looks like an issue with GitHub. GitHub should respect the cache control header of the original request, and not cache the redirect location.

**Comment by pierredup** [comment]
I don't think keeping headers from the original request is a good idea, especially since the original request is just a redirect, and one site shouldn't determine the headers to be used when redirecting to a different domain. That sounds like a big security issue. Instead I think shields.io should send the correct headers with dynamic badges

**Comment by GrahamCampbell** [comment]
> Instead I think shields.io should send the correct headers with dynamic badges

This isn't a dynamic badge though. :/

**Comment by GrahamCampbell** [comment]
I'm going to look into getting StyleCI to host the badges itself right now actually. :)

**Comment by GrahamCampbell** [comment]
Ok, the new code is deployed. We're no longer relying on shields.io. Our `/shield` urls now actually serve the svgs straight up.

**Comment by GrahamCampbell** [comment]
https://styleci.io/repos/16789051/shield?style=flat

**Comment by cordoval** [comment]
hmm still cannot get it to display green

**Comment by GrahamCampbell** [comment]
Yeh, github will have cached it for a while...

**Comment by GrahamCampbell** [comment]
Maybe contact github support and ask for them to flush the cache. They've flushed various other caches for me on my request before.

**Comment by cordoval** [comment]
:disappointed: of github

**Comment by GrahamCampbell** [comment]
This hack will work for now if you really want: https://github.com/gushphp/gush/pull/487.

**Comment by cordoval** [comment]
sweet! thanks @GrahamCampbell
