### ISSUE TITLE
The PHAR file containing dev dependencies

### ISSUE THREAD

**Issue by aik099** [gushphp/gush#491]
The "Hamcrest" library is contained within `gush.phar` file. If we remove it, then following warning will be shown on PHAR usage attempt:

```
PHP Warning:  require(phar://.../gush.phar/vendor/hamcrest/hamcrest-php/hamcrest/Hamcrest.php): failed to open stream: phar error: "vendor/hamcrest/hamcrest-php/hamcrest/Hamcrest.php" is not a file in phar "gush.phar" in phar://.../gush.phar/vendor/composer/autoload_real.php on line 54
```

Right now the only way to overcome this is to do:
```
composer install --no-dev
box build
composer install
```

**Comment by cordoval** [comment]
how did you trigger the warning? this is weird
we already do
```bash
d /var/www/vhosts/
cd gush-site
git remote update
git pull
sculpin generate --env=prod
cd output_prod
cp -rf * ../../gushphp.org/web/


cd /var/www/vhosts/gushphp.org
rm composer.lock
rm -rf vendor
git remote update
git pull
composer install --no-dev -o
cd web
box build -c ../box.json
chmod 644 gush.phar
```

**Comment by aik099** [comment]
As I said `if you exclude Hamcrest in box.json, then you will get the warning`. Currently of course no warning happens.

I wish that `box build` command would be able to handle this on it's own.

**Comment by cordoval** [comment]
i am not following why you would want to use hamcrest within gush?

**Comment by cordoval** [comment]
cc @sstok

**Comment by aik099** [comment]
I don't want Hamcrest within Gush, but by default the Box is only deleting selected folders under `/vendor` but isn't rebuilding Composer's autoloader. This creates a problem for Hamcrest library used by PHPUnit, because Hamcrest is including file with global function definitions in contrast to using auto-loading and that `include_once` statement is trying to include missing file, which creates a warning.

So if you don't do `composer install --no-dev` before `box build` then you'll get that warning. This is kind of stupid, because `box build` is supposed to be the only command to be executed to build PHAR, but instead we're forced to run extra commands.

**Comment by cordoval** [comment]
I think you are building the phar. The phar does not need to have any dev dependency and that is why the --no-dev is required. I don't think is box responsibility to ensure dev dependencies are around or not.
