### ISSUE TITLE
Installer using 1.16.1 version

### ISSUE THREAD

**Issue by aik099** [gushphp/gush#494]
I'm using installer to upgrade to latest Gush version (this is not easy knowing that almost all console scripts nowadays have `--self-update` option) and I'm getting 1.16.1 version back, while latest released is 1.17.0.

**Comment by cordoval** [comment]
yes this is my fault will update tonight the phar, i recommend cloning if you need it for right now

**Comment by aik099** [comment]
I'm not sure if installer does that, but maybe it should download version compatible with installer PHP version. For example I have PHP 5.4 installed on my development machine and I bet installer will get me 1.17.0 version back, which works on PHP 5.5+ only.

**Comment by cordoval** [comment]
if you want to install a pre gush release i recommend you check it out using the tag on releases tab on github and clone and build that. Unfortunately in the server there is only one phar and that is the latest version since we don't support release branches.
