### ISSUE TITLE
Update meta:header to work on less/scss files

### ISSUE THREAD

**Issue by aequasi** [gushphp/gush#501]

**Comment by cordoval** [comment]
i think this is just writing an adapter like we have for twig, css, js, php, what is the way you comment on less scss and i guess you want also sass, any other extension that you want to cover here? and what is the way of commenting on each one of them so to avoid problems?

**Comment by sstok** [comment]
less and scss are and extension of the CSS syntax.

Just add to `'scss' => new Meta\Text(), 'less' => new Meta\Text(),` to 
https://github.com/gushphp/gush/blob/master/src/Application.php#L366

Btw, these objects are re-usable so no need recreate them every time.
