### ISSUE TITLE
scrutinizer does it matter? or we can get rid of it?

### ISSUE THREAD

**Issue by cordoval** [gushphp/gush#510]

**Comment by GrahamCampbell** [comment]
At least disable it on PRs.

**Comment by cordoval** [comment]
is down now on badge on README.md on github

**Comment by cordoval** [comment]
i have used it very very few times...

**Comment by GrahamCampbell** [comment]
Maybe disable it then. :)

**Comment by cordoval** [comment]
let's wait for @sstok and other's vote on this, :+1: @GrahamCampbell

**Comment by pierredup** [comment]
:+1:

**Comment by cordoval** [comment]
thanks @pierredup :+1:

**Comment by cordoval** [comment]
done
