### ISSUE TITLE
Consider using console form library

### ISSUE THREAD

**Issue by AlexKovalevych** [gushphp/gush#511]
Just curious what you think about https://github.com/matthiasnoback/symfony-console-form. Does it worth to use it for console interactions?

**Comment by cordoval** [comment]
http://whateverthing.com/blog/2015/10/19/the-llama-commander/

**Comment by pierredup** [comment]
> http://whateverthing.com/blog/2015/10/19/the-llama-commander/

That doesn't look very flexible for what you want to accomplish here. It's a nice little library, but I think it's more suited for quick small simple console applications

**Comment by cordoval** [comment]
closing then
