### ISSUE TITLE
PullRequestFixerCommand doesn't actually update pull-request

### ISSUE THREAD

**Issue by sstok** [gushphp/gush#526]
The PullRequestFixerCommand only updates the local branch, but doesn't actually change the pull-request content. We should have two commands for this, one for the local branch and one for pull-requests.

**Comment by cordoval** [comment]
not sure i am following

**Comment by pierredup** [comment]
Instead of another command, how about just add a flag to the current command, like `--push`, which will then push the changes to the remote, which should update the PR (Note: I haven't had a look at that command in a while, so I might mis-understand what it does)

**Comment by sstok** [comment]
Thinking about this now we should only fix the pull-request content (remote branch not the local one as it could be outdated #519 ) and always push. If you want to do this local you can simple run php-cs-fixer manually and commit.

The command is more about contributor workflow, else you need run php-cs-fixer, commit, push with force (hoping you use the Gush command and not git push -f remote-name).

**Comment by cordoval** [comment]
I remember that I created this command to be run offline on local only and then if the user wants they can use gush for pushing it upstream. The added thing about this command is that it commits the fix automatically. This you can either revert or reset depending on whether you like it or not.

**Comment by sstok** [comment]
Would you vote moving it to the meta or branch command namespace then? Because it's not related to pull-request at all.

**Comment by cordoval** [comment]
yes it should be meta probably
