### ISSUE TITLE
Migration process between services ?

### ISSUE THREAD

**Issue by shulard** [gushphp/gush#527]
Hello !

I'm currently investigating a way to migrate some big projects from Bitbucket to Gitlab.

Gitlab give a built-in exporter but it does not work very well on huge issues list because it rely on HTTP (and the timeout is not really long).
The biggest project contains about 200 issues and I want to import all comments, attachments, assignement, meta. I already tried to build something but alone it's too much work on my free time for the moment :smile:

I found that project which seems really clean :+1: 

Is it in your plan to develop some migration process from one system to another ? Maybe I can help on that...
If it's not maybe you plan to handle export for these data ?

**Comment by cordoval** [comment]
there is already a command that attempts this, if you fix the adapters you perhaps can make this possible, take a stab
