### ISSUE TITLE
Tag name

### ISSUE THREAD

**Issue by GrahamCampbell** [gushphp/gush#538]
Shouldn't the last tag have been `1.19.0` rather than `1.19` to match the others?

**Comment by cordoval** [comment]
yeah, probably, does it matter though?

**Comment by cordoval** [comment]
what i mean is if this can cause troubles down the line, or everything remains the same. Do you want me to push remote the tag and push it again?

**Comment by GrahamCampbell** [comment]
I'm not massively bothered. I just thought I'd let you know in case you didn't realise. I've done similar things before since it's difficult to keep track of reach repos versioning standards, like, do we include a leading `v`, do we include a trailing `.0` on new minor releases, etc. ;)
