### ISSUE TITLE
http://gushphp.org/ domain does not exist

### ISSUE THREAD

**Issue by glensc** [gushphp/gush#547]
```
$ host gushphp.org
Host gushphp.org not found: 3(NXDOMAIN)
```

**Comment by cordoval** [comment]
yeah we closed the server not long ago. We are just going to try to just use github.com so we probably will upload things there.

**Comment by glensc** [comment]
i suggest to keep this issue open until then, so people don't report duplicate bugs and know you're working on this.

**Comment by Flyingmana** [comment]
Is there a way to support this? Because having the URL on the organization page and then no site reachable makes users probably a bit worry.

**Comment by cordoval** [comment]
he he, unfortunately means money, and I am not wanting to spend money on that convenience since it can just be cloned. :blush:

**Comment by glensc** [comment]
i guess @Flyingmana just offered $-help?

**Comment by Flyingmana** [comment]
I have at least enough idle server power, also I could offer a bit of time porting the website to githubpages, or another static site generator.
Is the Content of the Website somewhere to find currently?

**Comment by cordoval** [comment]
we actually let go of the domain name already and set on just having github repository being the true source basically.

**Comment by cordoval** [comment]
Thanks for your generosity though @Flyingmana. The website was in a repository that I deleted. There is a copy somewhere around on my disk just in case.

**Comment by aik099** [comment]
For now you can upload PHAR of Gush version into corresponding releases. Right now with website got people need to Clone gush repo to build a phar, which isn't very convenient.

The `core:update` command can be changed to download PHARs from GitHub releases as well.

**Comment by aik099** [comment]
Maybe it's also a good time to switch from https://github.com/kherge-abandoned/php-phar-update abandoned package used for updates to https://github.com/padraic/phar-updater , which has GitHub Releases update support built-in.

**Comment by cordoval** [comment]
i will close this now since with time it is evident that we are going github pages
