### ISSUE TITLE
Unable to use pull-request:create on forked repo-name mismatch

### ISSUE THREAD

**Issue by sstok** [gushphp/gush#548]
Say I have an organization 'rollerworks', with a repository 'datagrid'.
I fork the repository to my personal org (sstok), and then I rename the forked repository to rollerworks-datagrid (to prevent conflicts).

When I execute `pull-request:create` Gush will use the repository-name that is configured in the local file for *my* repository. But my repository is called 'rollerworks-datagrid', not 'datagrid'!
And the command fails with an API 404 error.

For now I can use the `--source-repo=` option but it's better not to require this.

Any idea's who this can be solved? It needs to be easy to use, and work for all adapters.

**Comment by cordoval** [comment]
you don't need to prevent any conflicts, you should not have renamed the repository.
I think this is really an edge case. :blush:

**Comment by sstok** [comment]
Agreed.
