### ISSUE TITLE
add command to sign a release/download

### ISSUE THREAD

**Issue by Flyingmana** [gushphp/gush#551]
I would like to have a command to add a signature to a release/download

command would be `release:sign` with an `tag` argument.

it would download the .zip and .tar file and create a signature for each with the naming schema `{filename}.{extension}.sig` if there is already such a sig file, it would download it and just append the signature (gpg supports multiple signatures)

will probably create this command myself in then ext weeks

**Comment by cordoval** [comment]
:+1: it will be welcomed into this repo

**Comment by cordoval** [comment]
testing

**Comment by cordoval** [comment]
I guess you did not create it @Flyingmana ? if so then reopen and submit PR
