### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by chalasr** [gushphp/gush#552]
Hi there!

First, thank's for this tool that sounds amazing.
But,  I can't understand why it is not documented anywhere... How to use it?!

With a bit of imagination, I added `gushphp/gush` as global composer requirement, then I found the `gush` executable. Now I hope I'll be able to use it by squinting on your two (video) demonstrations.

Plus, [the website](http://gushphp.org/) seems to be broken (No working view, an error message on the homepage saying that it can't find a result for my search... There is no search!!).

My question is: Am I missing something? 
Otherwise, is the documentation in the pipes?

Also, I saw [this](https://github.com/cordoval/gush/blob/master/README.md) but it doesn't help at all, as the installer link is broken.

Thank's

**Comment by sstok** [comment]
Good to here your support, the website is down because the project lead did not have enough funding to keep it up. You actually need to use the Phar version (which is no longer available...) and not the Composer version as that is no longer supported.

I will compile a Phar and see if I can add it to the downloads. Give me a sec.

**Comment by GrahamCampbell** [comment]
> the website is down

ACtually, someone else has bought the domain now. The website is something else!

**Comment by chalasr** [comment]
@sstok I think it's a pity that a such interesting project cannot be tried easily.

What do you think about writing a simple document listing the most important commands for main use cases? (that could be done in the README for instance) 

I'd like to help you in this way but because of the lack of doc, I don't have a sufficient knowledge of gush :/

**Comment by sstok** [comment]
Great... we can still use GitHub for website hosting though 👍 I actually need to speak the project lead about some other stuff.

For now you can find the phar on https://github.com/gushphp/gush/releases/download/1.19.1/gush.phar
Please report back if doesn't work because I'm using PHP 7 which may have caused some newer versions.

You can find the list of commands with `gush.phar list`, you should be prompted to fill-in your GitHub credentials whenever you execute something that requires them.

For basic usage.

First run: `gush.phar core:configure` to set-up your adapter credentials.
And then run `gush.phar core:init` in the repository you want to enable gush for (not required but speeds-up application).

Good luck, and please ask if you need help with something.

**Comment by sstok** [comment]
Oh and there is an `util:documentation` command that generates the documention in the web folder.

**Comment by chalasr** [comment]
@sstok Wow.. So the only missing thing is to host the generated doc, right?

Thank's for your previous comment, it should be widely sufficient.
I'll not hesitate to open issues/PRs in case of problems.

Keep me informed when doc is published.

**Comment by sstok** [comment]
Will do, thanks for helping with this 👍 I'm to spend some much needed love on the Gush project to get it moving again.

**Comment by cordoval** [comment]
I closed the site because is better this way. But yeah we need to write some gh-pages stuff to replace docu. If you do this @sstok let me know so we can put it up on github pages. 👍

**Comment by sstok** [comment]
Creating a gh-pages branch should actually set it up automatically for gushphp.github.io/gush

**Comment by sstok** [comment]
OK https://gushphp.github.io/gush/ is now live. But there is no actual content yet :)

**Comment by chalasr** [comment]
Good to here!
If you don't yet did it tomorrow, I'll try to generate the doc as you said, then make a (jekyll) build and submit a PR.

Thank's for your quick reaction @sstok, feel free to close this now, otherwise I'll do it as soon as the doc is online.

**Comment by sstok** [comment]
Note that you need to update the `util:documentation` command to make it compatible for Jekyll 👍

**Comment by pierredup** [comment]
How about creating a `gushphp.github.io` repository, then the documentation can live outside of the main repo, and also you get a cleaner domain to use like https://gushphp.github.io instead of https://gushphp.github.io/gush/

**Comment by chalasr** [comment]
Is there any news on this?

Also after tried it today, this tool is really nice 👍 
Great work guys! (more reason to document it as well)

**Comment by cordoval** [comment]
@chalasr nice that you liked it, yeah if you are familiar with getting the docu from the console then it should be good enough, but yeah we need docu. Will land hopefully soon. Can you do an extensive review of gush? i am trying to find ways to simplify and trim things that are unnecessary. 

The initial flow was very simple and i want to keep it that way for obvious reasons. The goal is automation with one command that can be quick (not the case necessarily) and almost unique to say branch with name of ticket or arbitrary commit push sequence and opening the PR really fast, then upon merging it it will switch branches and keep pushing. That is the idea, everything else should be relegated to minimum lines of code and simplicity.

**Comment by chalasr** [comment]
@cordoval I'm not really talking about the documentation of the commands themselves, the doc from the console is effectively clear enough, plus the two links given in the README already present the main commands.
 
That's more "from where do I start?", some basics such as the right way to get it installed, how to have the binary available and so on. Also I agree with you about they are not so difficult to guess, but I think it is always better to have this kind of introductions.
I think people can look for these docs and they can be lost (maybe definitely). 
I'll try to quickly propose you a small document with just the most important, no fuss no muss.

> Can you do an extensive review of gush? i am trying to find ways to simplify and trim things that are unnecessary.

Sure, gladly! Will try to look at it this week-end, I'll give you some feedback when it's done.
