### ISSUE TITLE
CMD git rev-parse --abbrev-ref HEAD CMD git push cordoval -u thursday-of-deploy

### ISSUE THREAD

**Issue by cordoval** [gushphp/gush#555]
it is not git push cordoval -u ...
but git push -u cordoval 👍 

i will fix it this weekend

**Comment by cordoval** [comment]
my bad!

**Comment by sstok** [comment]
Is this still relevant? or was it a user error 😄

**Comment by sstok** [comment]
Please see https://github.com/gushphp/gush/pull/643

**Comment by cordoval** [comment]
great catch @sstok, like the old times 👍
