### ISSUE TITLE
[Gush org] Remove priority labels for issues and pull-requests

### ISSUE THREAD

**Issue by sstok** [gushphp/gush#562]
Taking this from the ZeroMQ C4: https://hintjens.gitbooks.io/social-architecture/content/chapter1.html#self-organization

> In ZeroMQ, we removed all assigned tasks from the community. For example,
we don't accept feature requests. If someone wants a feature,
they either send us a patch, or offer someone money to make the change,
or they wait. This means people only make changes they really need to make.

In the Gush organization have various priority labels (critical, high, nice to have) to indicate the importance, but there is a major problem with this system.

It only indicates the importance for that person, for example #500 is marked critical (since late 2015), and feature requests are another beast (why is this marked 'low priority'? I "need" it now!).

*An even better example is the BitBucket-site issue tracker, multiple issues were marked critical for over 5 years! If something is critical is should be fixed right now, not tomorrow or two hours from now.*

Plus, in the past some issues were marked critical while they were a simple user error.

You get the point... it gives a wrong impression and false information.

Instead we can remove remove all priority labels and thread all issues as equal.

For features we follow a simple rule: "If you want a feature, either send a patch (pull request), offer someone money to make the change, or wait. Remember this is a community-driven project, not everyone needs the same features".

**Comment by cordoval** [comment]
I couldn't find where is the priority in the code you spoke about. I think this is not that critical 😊, because i think is more about the use case, and how admins use it. It is ok to have more important issues than others. And if gush is already supporting this then it should be fine, i don't remember using them.

**Comment by sstok** [comment]
I'm talking about the Gush repository 😜 https://github.com/gushphp/gush/labels

**Comment by cordoval** [comment]
I do pay attention to those labels. And if you label it critical i know it is important for you 👍 . That is good and is communication between us more than anything.
