### ISSUE TITLE
[Bitbucket] Disallow forking repo to same org

### ISSUE THREAD

**Issue by sstok** [gushphp/gush#580]
BitBucket allows (allowed?) to fork a repository to the same organization (repo1 in org "acme", fork repo1 to "acme") but this breaks the workflow of Gush so instead this should throw an exception that Gush doesn't support this.

**Comment by sstok** [comment]
http://restbrowser.bitbucket.org/ 🙄
"Rest browser discontinued". 

You are kidding me... Really BitBucket you have the worst documented API I know of then you take down the only the thing that helped my solve an issue easily. So glad *I'm* using GitHub.

**Comment by GrahamCampbell** [comment]
Totally!

**Comment by sstok** [comment]
It just keeps getting worse, now in 2.0 there is no endpoint for creating forks 👏 
And in 1.0 you can create a fork only your current account, if you want it for a different organization you need to update it afterwards...

But wait there is more: `<ul class="errorlist"><li>name<ul class="errorlist"><li>You already have a repository with this name.</li></ul></li></ul>`

That is with `Content-Type: application/json; charset=utf-8` and `?format=json` 💃

**Comment by cordoval** [comment]
so we can close this ticket since it is a no issue?

**Comment by sstok** [comment]
Technically it is an issue but BitBucket already gives a error when this happens.
Only thing that's actually broken is forking to another organization then user's account, I'm working on this.

**Comment by cordoval** [comment]
i am not sure that is a common scenario so 👎
