### ISSUE TITLE
[GitLab] getPullRequestCommits has a noop implementation

### ISSUE THREAD

**Issue by sstok** [gushphp/gush#581]
https://github.com/gushphp/gush/blob/c6a283da6a8d6b21fdb23cf9b2b8e07470c17340/src/ThirdParty/Gitlab/Adapter/GitLabRepoAdapter.php#L194 

@shulard can you please a look a this, the GitLab API does support an endpoint for this 👍 the method is used when merging a pull-request to create a commit message and validate the authors when squash is asked.

**Comment by shulard** [comment]
Hello !

Yes I'll take a look at this missing function. I'll try to push some code during this week.

**Comment by shulard** [comment]
Can you please assign me to that issue ?

**Comment by sstok** [comment]
Done 👍

**Comment by shulard** [comment]
For the moment the Gitlab API library has not the ability to retrieve merge requests commit... I've created a PR on that project: m4tthumphrey/php-gitlab-api/pull/139.

When it'll be merged, we can update the dependency and merge that pull-request. To check here, you must use this specific version: https://github.com/shulard/php-gitlab-api
