### ISSUE TITLE
[Adapter] Allow to configure forks organization

### ISSUE THREAD

**Issue by sstok** [gushphp/gush#583]
Some people including @GrahamCampbell use a separate organization for keeping there forks but Gush assumes that the forks organization equals the username (thus breaking for some commands).

Add an extra option for all repo configurators to select a different forks-organization.
And update the usage of username for org to use the option, and fallback to the username when it's not set (old configuration).

**Comment by cordoval** [comment]
i am not feeling confortable breaking some preconceptions Gush is based on. This needs more discussion.

**Comment by sstok** [comment]
In practice you replace this `$this->getParameter($input, 'authentication')['username']` with this `$this->getParameter($input, 'authentication')['fork-org']` (and fallback to the previous one when no value is set).
