### ISSUE TITLE
docker instructions

### ISSUE THREAD

**Issue by glensc** [gushphp/gush#625]
the instructions in [README.md](https://github.com/gushphp/gush/blame/b05fd1c4323e33c7a60e438c796d2c05467c668a/README.md#L23-L29) are slightly incorrect

it the script presented there uses [gush](https://github.com/gushphp/gush/blob/b05fd1c4323e33c7a60e438c796d2c05467c668a/gush.dist#L12) named image, but [no such image](https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=gush&starCount=0) is published

so the instructions should be updated to build it first locally:
```
git clone ...
docker build -t gush
```

... or appropriate image actually published to docker hub

**Comment by sstok** [comment]
It seems #612 broke this, ping @cordoval
